apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dittos.iot.eclipse.org
spec:
  group: iot.eclipse.org
  scope: Namespaced
  names:
    plural: dittos
    singular: ditto
    kind: Ditto
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              enableDummyAuth:
                type: boolean
                description: Enable the "dummy authentication" mode.
              createDefaultUser:
                type: boolean
                description: Create the default "ditto" user when initially deploying.
              devopsSecureStatus:
                type: boolean
                description: Secure the devops status information.
              version:
                type: string
                description: Override the image version of the Ditto images.
